#!/bin/sh

genkernel initramfs --luks

echo "----------------------------------------------------------"
echo "aa-genkernel executed successfully! "
echo "----------------------------------------------------------"
